"""
Project: E-Commerce Business Performance Analytics

Script:
03_payments_analysis.py

Author:
Noel Channayil

Description:
Loads the Olist order payments dataset and analyzes total payment value
generated by each payment method.

Dataset:
Dataset/olist_order_payments_dataset.csv
"""

from pathlib import Path
import pandas as pd

# -------------------------------------------------------------------
# Define project directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BASE_DIR / "Dataset"

# -------------------------------------------------------------------
# Load dataset
# -------------------------------------------------------------------

payments = pd.read_csv(
    DATASET_DIR / "olist_order_payments_dataset.csv"
)

# -------------------------------------------------------------------
# Payment Method Analysis
# -------------------------------------------------------------------

payment_analysis = (
    payments
    .groupby("payment_type")["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

# -------------------------------------------------------------------
# Display Results
# -------------------------------------------------------------------

print("\nRevenue by Payment Method\n")
print(payment_analysis)