"""
Project: E-Commerce Business Performance Analytics

Script:
11_state_revenue_analysis.py

Author:
Noel Channayil

Description:
Loads the Olist customers, orders, and order payments datasets,
merges them, and analyzes total revenue generated by each
customer state.

Datasets:
- olist_customers_dataset.csv
- olist_orders_dataset.csv
- olist_order_payments_dataset.csv
"""

from pathlib import Path
import pandas as pd

# -------------------------------------------------------------------
# Define project directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BASE_DIR / "Dataset"

# -------------------------------------------------------------------
# Load datasets
# -------------------------------------------------------------------

customers = pd.read_csv(
    DATASET_DIR / "olist_customers_dataset.csv"
)

orders = pd.read_csv(
    DATASET_DIR / "olist_orders_dataset.csv"
)

payments = pd.read_csv(
    DATASET_DIR / "olist_order_payments_dataset.csv"
)

# -------------------------------------------------------------------
# Merge Orders with Customers
# -------------------------------------------------------------------

state_df = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="left"
)

# -------------------------------------------------------------------
# Merge Payment Information
# -------------------------------------------------------------------

state_df = pd.merge(
    state_df,
    payments,
    on="order_id",
    how="left"
)

# -------------------------------------------------------------------
# Revenue by Customer State
# -------------------------------------------------------------------

state_revenue = (
    state_df
    .groupby("customer_state")["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

# -------------------------------------------------------------------
# Display Results
# -------------------------------------------------------------------

print("\nRevenue by Customer State\n")
print(state_revenue)