"""
Project: E-Commerce Business Performance Analytics

Script:
12_state_revenue_chart.py

Author:
Noel Channayil

Description:
Loads the Olist customers, orders, and order payments datasets,
calculates revenue generated by each customer state, and visualizes
the Top 10 states by revenue using a bar chart.

Datasets:
- olist_customers_dataset.csv
- olist_orders_dataset.csv
- olist_order_payments_dataset.csv
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------------------------------------------
# Define project directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BASE_DIR / "Dataset"

# -------------------------------------------------------------------
# Load datasets
# -------------------------------------------------------------------

customers = pd.read_csv(
    DATASET_DIR / "olist_customers_dataset.csv"
)

orders = pd.read_csv(
    DATASET_DIR / "olist_orders_dataset.csv"
)

payments = pd.read_csv(
    DATASET_DIR / "olist_order_payments_dataset.csv"
)

# -------------------------------------------------------------------
# Merge Orders with Customers
# -------------------------------------------------------------------

state_df = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="left"
)

# -------------------------------------------------------------------
# Merge Payment Information
# -------------------------------------------------------------------

state_df = pd.merge(
    state_df,
    payments,
    on="order_id",
    how="left"
)

# -------------------------------------------------------------------
# Calculate Top 10 States by Revenue
# -------------------------------------------------------------------

state_revenue = (
    state_df
    .groupby("customer_state")["payment_value"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

# -------------------------------------------------------------------
# Plot Revenue by State
# -------------------------------------------------------------------

plt.figure(figsize=(10, 6))

state_revenue.plot(
    kind="bar",
    width=0.8
)

plt.title("Top 10 States by Revenue", fontsize=16)

plt.xlabel("Customer State")

plt.ylabel("Revenue")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()

plt.show()