"""
Project: E-Commerce Business Performance Analytics

Script:
13_seller_revenue_analysis.py

Author:
Noel Channayil

Description:
Loads the Olist order items dataset and calculates the
total revenue generated by each seller. The script identifies
the highest revenue-generating sellers to support seller
performance analysis.

Dataset:
- olist_order_items_dataset.csv
"""

from pathlib import Path
import pandas as pd

# -------------------------------------------------------------------
# Define project directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BASE_DIR / "Dataset"

# -------------------------------------------------------------------
# Load dataset
# -------------------------------------------------------------------

order_items = pd.read_csv(
    DATASET_DIR / "olist_order_items_dataset.csv"
)

# -------------------------------------------------------------------
# Calculate Revenue by Seller
# -------------------------------------------------------------------

seller_revenue = (
    order_items
    .groupby("seller_id")["price"]
    .sum()
    .sort_values(ascending=False)
)

# -------------------------------------------------------------------
# Display Results
# -------------------------------------------------------------------

print("Top 20 Sellers by Revenue\n")

print(seller_revenue.head(20))