"""
Project: E-Commerce Business Performance Analytics

Script:
14_seller_concentration_analysis.py

Author:
Noel Channayil

Description:
Calculates seller revenue concentration by determining
how much of the total revenue is generated by the
top 10 sellers. This helps evaluate seller dependency
and revenue distribution across the marketplace.

Dataset:
- olist_order_items_dataset.csv
"""

from pathlib import Path
import pandas as pd

# -------------------------------------------------------------------
# Define project directory
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BASE_DIR / "Dataset"

# -------------------------------------------------------------------
# Load dataset
# -------------------------------------------------------------------

order_items = pd.read_csv(
    DATASET_DIR / "olist_order_items_dataset.csv"
)

# -------------------------------------------------------------------
# Calculate Seller Revenue
# -------------------------------------------------------------------

seller_revenue = (
    order_items
    .groupby("seller_id")["price"]
    .sum()
    .sort_values(ascending=False)
)

# -------------------------------------------------------------------
# Calculate Revenue Concentration
# -------------------------------------------------------------------

total_revenue = seller_revenue.sum()

top10_revenue = seller_revenue.head(10).sum()

contribution = (
    top10_revenue / total_revenue
) * 100

# -------------------------------------------------------------------
# Display Results
# -------------------------------------------------------------------

print("Total Revenue")
print(round(total_revenue, 2))

print("\nTop 10 Sellers Revenue")
print(round(top10_revenue, 2))

print("\nTop 10 Seller Contribution (%)")
print(round(contribution, 2))